fan:
  origin: User
  target: Artist
  assoc: ArtistUser
  kind: 1
  label: user_top_artist
  number: 4
  url: "fan"
  sort: "random()"
attend:
  origin: User
  target: Event
  assoc: EventUser
  kind: 1
  label: user_attend_event
  number: 3
  url: "attend"
  sort: "attendance DESC"
artist_event:
  origin: Artist
  target: Event
  assoc: ArtistEvent
  kind: 1
  label: user_attend_event
  number: 3
  url: "attend"
  sort: "attendance DESC"
