fan:
  origin: User
  target: Artist
  assoc: ArtistUser
  kind: 1
  label: user_top_artist
  number: 3
  url: "fan"
  sort: "1"
attend:
  origin: User
  target: Event
  assoc: EventUser
  kind: 1
  label: user_attend_event
  number: 2
  url: "attend"
  sort: "attendance DESC"
artist_event:
  origin: Artist
  target: Event
  assoc: ArtistEvent
  kind: 1
  label: user_attend_event
  number: 2
  url: "attend"
  sort: "attendance DESC"
similar_artist:
  origin: Artist
  target: Artist
  assoc: Similar
  kind: 1
  label: user_top_artist
  number: 2
  url: "fan"
  sort: "1"
listened-to:
  origin: User
  target: Track
  assoc: TrackUser
  kind: 1
  label: user_recent_track
  number: 2
  url: "listened-to"
  sort: "1"
similar_tracks:
  origin: Track
  target: Track
  assoc: SimilarTrack
  kind: 1
  label: user_recent_track
  url: "listened-to"
  number: 3
  sort: "1"
top_tracks:
  origin: Artist
  target: Track
  assoc: ArtistTrack
  kind: 1
  label: user_recent_track
  url: "listened-to"
  number: 3
  sort: "1"
event_headliners:
  origin: Event
  target: Artist
  assoc: ArtistEvent
  kind: 2
  label: user_top_artist
  url: "fan"
  number: 3
  sort: "1"
track_artist:
  origin: Track
  target: Artist
  assoc: ArtistTrack
  kind: 2
  label: user_top_artist
  url: "fan"
  number: 1
  sort: "1"
